# Generated by Django 4.2.6 on 2023-10-30 10:29

import book_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('author', models.CharField(max_length=55)),
                ('genre', models.CharField(max_length=55)),
                ('publisher', models.CharField(max_length=30)),
                ('release_year', models.IntegerField(validators=[book_management.models.year_validation])),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
